
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;


public class GUI_KUSTOMER extends javax.swing.JFrame {

    Tree tree = new Tree();
    LinkedList<TreeNode> list;
    
    public GUI_KUSTOMER() {
        initComponents();
        
        // MAKANAN
        tree.add(new TreeNode("Chicken Bbq Grill", "Makanan", 43000));
        tree.add(new TreeNode("Wagyu", "Makanan", 121000));
        tree.add(new TreeNode("Rib Eye Import", "Makanan", 104000));
        tree.add(new TreeNode("Sirloin Import", "Makanan", 98000));
        tree.add(new TreeNode("Blackpepper", "Makanan", 46000));
        tree.add(new TreeNode("Chicken Double Cheese Sauce ", "Makanan", 45000));
        tree.add(new TreeNode("Sirloin Cheese Sauce", "Makanan", 30000));
        tree.add(new TreeNode("Chicken Rice", "Makanan", 35000));
        tree.add(new TreeNode("Chicken Salad", "Makanan", 29000));
        tree.add(new TreeNode("Chicken Steak", "Makanan", 44000));
        
        // MINUMAN
        tree.add(new TreeNode("MilkShake Vanilla", "Minuman", 22000));
        tree.add(new TreeNode("MilkShake Mocca", "Minuman", 23000));
        tree.add(new TreeNode("Orange Float", "Minuman", 24000));
        tree.add(new TreeNode("Caramel Machiato", "Minuman", 27000));
        tree.add(new TreeNode("Lemon Tea", "Minuman", 19000));
        
        tree.add(new TreeNode("Kentang Lokal", "Snack", 11000));
        tree.add(new TreeNode("Cheese Fries", "Snack", 19000));
        tree.add(new TreeNode("Fries", "Snack", 13000));
        tree.add(new TreeNode("Drum And Chips", "Snack", 26000));
        tree.add(new TreeNode("Cheese Wedges", "Snack", 17000));
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screenSize.width - this.getWidth()) / 2;
        int y = (screenSize.height - this.getHeight()) / 2;
        this.setLocation(x, y);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jenis = new javax.swing.JComboBox<>();
        cariText = new javax.swing.JTextField();
        search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel.setRowHeight(30);
        jScrollPane1.setViewportView(tabel);
        if (tabel.getColumnModel().getColumnCount() > 0) {
            tabel.getColumnModel().getColumn(0).setResizable(false);
            tabel.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel2.setBackground(new java.awt.Color(252, 249, 181));

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama", "Harga" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });

        cariText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariTextActionPerformed(evt);
            }
        });

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(search)
                .addGap(18, 18, 18)
                .addComponent(cariText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jenis, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(cariText, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 946, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cariTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariTextActionPerformed

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        
//if ("Close".equals(ComboBox.getSelectedItem())) {
//        // Tutup frame atau form saat "cancel" dipilih
//        Close.dispose();
//    } else {
        // Logika atau tindakan yang sesuai jika opsi lain dipilih
    

        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabel.getModel();
        
        int rowCount = model.getRowCount();
            if (rowCount > 0) {
                model.setRowCount(0);
            }
        try {
        if (jenis.getSelectedItem().equals("Nama")){
            
            tree.getNodeByName(cariText.getText());
            list = tree.nodes;
            
            if (list.size() != 0) {

                while (list.size() != 0) {

                    TreeNode node = list.pop();
                    Object[] data = {node.getNamaItem(), node.getHarga()};
                    model = (DefaultTableModel) tabel.getModel();
                    model.addRow(data);

                }
            } else {
                Object[] data = {"Pencarian tidak ditemukan", null};
                model = (DefaultTableModel) tabel.getModel();
                model.addRow(data);
            }
            tree.reset();
    
        } else if (jenis.getSelectedItem().equals("Harga")){
        
            tree.getNodeByPrice(Double.parseDouble(cariText.getText()));
            list = tree.nodes;
            
            if (list.size() != 0) {
                while (list.size() != 0) {
                    TreeNode node = list.pop();
                    Object[] data = {node.getNamaItem(), node.getHarga()};
                    model = (DefaultTableModel) tabel.getModel();
                    model.addRow(data);
                }
            } else {
                
                Object[] data = {"Pencarian tidak ditemukan", null};
                model = (DefaultTableModel) tabel.getModel();
                model.addRow(data);
            
            }
            tree.reset();
   
    }
        } catch (NumberFormatException e){
            
        }
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_KUSTOMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_KUSTOMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_KUSTOMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_KUSTOMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_KUSTOMER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cariText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JButton search;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables

    
}
